import type { Project } from "@/lib/types";

export const PROJECTS: Project[] = [
  {
    id: "p1",
    name: "Home Renovation",
    description: "Track tasks and dependencies for the renovation plan.",
    tasks: [
      {
        id: "t1",
        projectId: "p1",
        title: "Finalize budget & scope",
        description: "Confirm scope, budget cap, and timeline.",
        status: "todo",
        assignedTo: ["You"],
        configuration: { priority: "high" },
        dependencies: [],
      },
      {
        id: "t2",
        projectId: "p1",
        title: "Hire contractor",
        description: "Shortlist vendors and schedule walkthroughs.",
        status: "in_progress",
        assignedTo: ["Alex"],
        configuration: { priority: "medium" },
        dependencies: [],
      },
      {
        id: "t3",
        projectId: "p1",
        title: "Order materials",
        description: "Place orders for paint, flooring, and fixtures.",
        status: "done",
        assignedTo: ["Sam"],
        configuration: { priority: "low" },
        dependencies: [],
      },
      {
        id: "t7",
        projectId: "p1",
        title: "Electrical wiring inspection",
        description: "Schedule and complete electrical safety inspection.",
        status: "todo",
        assignedTo: ["Inspector"],
        configuration: { priority: "high" },
        dependencies: ["t3"],
      },
      {
        id: "t8",
        projectId: "p1",
        title: "Paint selection",
        description: "Choose colors for walls, trim, and accents.",
        status: "todo",
        assignedTo: ["Designer"],
        configuration: { priority: "medium" },
        dependencies: [],
      },
      {
        id: "t9",
        projectId: "p1",
        title: "Final walkthrough",
        description: "Review all completed work and create punch list.",
        status: "todo",
        assignedTo: ["You", "Contractor"],
        configuration: { priority: "low" },
        dependencies: ["t7", "t8"],
      },
    ],
  },
  {
    id: "p2",
    name: "Product Launch",
    description: "Coordinate launch tasks across teams.",
    tasks: [
      {
        id: "t4",
        projectId: "p2",
        title: "Finalize launch messaging",
        description: "Lock headline, value props, and email copy.",
        status: "todo",
        assignedTo: ["Marketing"],
        configuration: { priority: "high" },
        dependencies: [],
      },
      {
        id: "t5",
        projectId: "p2",
        title: "QA + bug bash",
        description: "Run regression and triage critical issues.",
        status: "in_progress",
        assignedTo: ["Eng"],
        configuration: { priority: "high" },
        dependencies: [],
      },
      {
        id: "t6",
        projectId: "p2",
        title: "Publish release notes",
        description: "Draft notes and align with support.",
        status: "done",
        assignedTo: ["PM"],
        configuration: { priority: "medium" },
        dependencies: [],
      },
      {
        id: "t10",
        projectId: "p2",
        title: "Social media campaign",
        description: "Create posts for Twitter, LinkedIn, and Instagram.",
        status: "in_progress",
        assignedTo: ["Marketing"],
        configuration: { priority: "high" },
        dependencies: ["t4"],
      },
      {
        id: "t11",
        projectId: "p2",
        title: "Customer onboarding guide",
        description: "Write step-by-step setup documentation.",
        status: "todo",
        assignedTo: ["Support"],
        configuration: { priority: "medium" },
        dependencies: ["t6"],
      },
      {
        id: "t12",
        projectId: "p2",
        title: "Launch day monitoring",
        description: "Set up error tracking and performance dashboards.",
        status: "todo",
        assignedTo: ["DevOps"],
        configuration: { priority: "high" },
        dependencies: ["t5"],
      },
    ],
  },
];
